back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@frontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"