<?php

namespace BackBundle\Repository;

/**
 * ArticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticRepository extends \Doctrine\ORM\EntityRepository
{
}
