<?php

namespace BackBundle\Repository;

/**
 * AteliersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AteliersRepository extends \Doctrine\ORM\EntityRepository
{
}
