<?php

namespace BackBundle\Repository;

/**
 * LivreOrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreOrRepository extends \Doctrine\ORM\EntityRepository
{
}
