<?php

namespace BackBundle\Repository;

/**
 * TissusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TissusRepository extends \Doctrine\ORM\EntityRepository
{
}
